name: flutter_firebase_template
description: A Flutter Firebase template with authentication, Firestore, and more.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  cloud_functions: ^5.6.2
  firebase_storage: ^12.4.10

  # State Management
  flutter_bloc: ^9.1.1
  provider: ^6.1.5

  # UI & Fonts
  google_fonts: ^6.3.3

  # Utilities
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1
  intl: ^0.20.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

